
server:
  port: 8082
  #port: 8083
  servlet:
    context-path: /

spring:
  application:
    name: user

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true