server:
  port: 8761
  
spring:
  application:
    name: eurekaCenter

eureka: 
  client:
    register-with-eureka: false
    fetch-registry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/