server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: sales

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true